
name: CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: douyin
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      


      
#       - name: Setup MySQL
#         uses: mirromutth/mysql-action@v1.1
#         with:
#             host port: 3306
#             container port: 3306
#             character set server: utf8mb4
#             collation server: utf8mb4_general_ci
#             mysql root password: mysql
#             mysql database: douyin
#             mysql user: mysql
#             mysql password: mysql

      - name: Setup Ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: oss-cn-shenzhen.aliyuncs.com
          access-key-id: oss 
          access-key-secret: oss
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

